/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.autonoma.MC.ui;

import co.edu.autonoma.MC.cliente.elements.Cliente;
import co.edu.autonoma.MC.juego.elements.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuela Cardona
 */
public class LoginWindow extends javax.swing.JFrame {

    Cliente cliente;
    
    /**
     * Creates new form Login
     * @param cliente
     */
    public LoginWindow(Cliente cliente) {
        initComponents();
        
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelBienvenida = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        labelIp = new javax.swing.JLabel();
        txtFIp = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        labelImgJugador = new javax.swing.JLabel();
        labelImgJugadora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        labelBienvenida.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        labelBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenida.setText(" Stone-Paper-Scissors World");

        labelNombre.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre: ");

        labelIp.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        labelIp.setForeground(new java.awt.Color(255, 255, 255));
        labelIp.setText("Ip:");

        txtFIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFIpActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        labelImgJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Jugador.png"))); // NOI18N

        labelImgJugadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Jugadora.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(labelImgJugador)
                .addGap(35, 35, 35)
                .addComponent(labelImgJugadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(labelIp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFIp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelBienvenida)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImgJugador)
                    .addComponent(labelImgJugadora))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtFNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIp)
                    .addComponent(txtFIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnEntrar)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIpActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        String nombreJugador = txtFNombre.getText();
        
        this.cliente.setNombre(nombreJugador);
        
        this.cliente.setIpServidor(txtFIp.getText());
        
        if(this.cliente.getNombre().trim().isEmpty() | this.cliente.getIpServidor().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Completar los datos del login", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        boolean conexion = this.cliente.conectar();
        
        if(conexion){
            
            Jugador jugadorLocal = this.cliente.crearJugador(nombreJugador);
            
            if(jugadorLocal!=null){
                Mundo mundo = new Mundo(0,0,500,500);
                mundo.addSprite(jugadorLocal);

                MundoWindow mundoWindow = new MundoWindow();
                mundoWindow.setCliente(this.cliente);
                mundoWindow.setMundo(mundo);

                mundo.setGraphicContainer(mundoWindow);

                mundoWindow.setTitle("ROCK-PAPER-SCISSORS WORLD");
                mundoWindow.setLocationRelativeTo(this);
                mundoWindow.setVisible(true);

                this.cliente.iniciarEntradaMulticast(mundoWindow);

                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "LOGIN WINDOWS=> No se puede unir a la sesion actual, intente mas tarde");
            }            
        }else{
            JOptionPane.showMessageDialog(this, "LOGIN WINDOWS=> Error conectando con el servidor solicitado", "Conexión", JOptionPane.INFORMATION_MESSAGE);
        } 
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JLabel labelImgJugador;
    private javax.swing.JLabel labelImgJugadora;
    private javax.swing.JLabel labelIp;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField txtFIp;
    private javax.swing.JTextField txtFNombre;
    // End of variables declaration//GEN-END:variables
}
